=== josmartinezbe/20252094013/xml/facturacionxsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="servicios">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="geograficos"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="geograficos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="encabezado"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="encabezado">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="numero-factura"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="numero-factura">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="numero" type="xs:string"/>
        <xs:element name="fecha" type="xs:date"/>
        <xs:element ref="vendedor"/>
        <xs:element ref="cliente"/>
        <xs:element ref="servicio" maxOccurs="unbounded"/>
        <xs:element ref="total"/>
        <xs:element name="condiciones-pago" type="xs:string"/>
        <xs:element name="plazo-de-pago-dias" type="xs:integer"/>
        <xs:element name="notas-pago" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="vendedor">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="codigo" type="xs:string"/>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="telefono" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="cliente">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="nit" type="xs:string"/>
        <xs:element name="cedula" type="xs:string"/>
        <xs:element name="ciudad" type="xs:string"/>
        <xs:element name="direccion" type="xs:string"/>
        <xs:element name="telefono" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="servicio">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="descripcion" type="xs:string"/>
        <xs:element name="cantidad" type="xs:integer"/>
        <xs:element name="precio" type="xs:integer"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="total">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="subtotal" type="xs:integer"/>
        <xs:element name="descuentos" type="xs:integer"/>
        <xs:element name="impuentos" type="xs:string"/>
        <xs:element name="total-pago" type="xs:integer"/>
        <xs:element name="moneda" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== josmartinezbe/20252094013/20252094013/xml/facturacion.xml
<?xml version= "1.0" encoding="UTF-8"?>
<servicios xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="facturacionxsd.xsd">
	<geograficos>
		<encabezado>
			<numero-factura>
				<numero>001</numero>
				<fecha>2025-08-30</fecha>		
				<vendedor>
					<codigo>2025209401</codigo>
					<nombre>Johan Sebastian Martinez</nombre>
					<telefono>3015778544</telefono>
				</vendedor>
				<cliente>
					<nombre>Catalina Perez</nombre>
					<nit>900124798</nit>
					<cedula>34655721</cedula>
					<ciudad>San Juan</ciudad>
					<direccion>Calle 34 # 74 13 </direccion>
					<telefono>3418997544</telefono>
				</cliente>
				<servicio>
					<descripcion>
					Conusltoría y Aseoría en el Mercado ambiental
					</descripcion>
					<cantidad>1</cantidad>
					<precio>500</precio>
				</servicio>
				<servicio>
					<descripcion>
					Evaluación de áreas para compensaciones
					</descripcion>
					<cantidad>3</cantidad>
					<precio>200</precio>
				</servicio>
				<servicio>
					<descripcion>
					Levantamiento fotogrametria
					</descripcion>
					<cantidad>1</cantidad>
					<precio>500</precio>
				</servicio>
				<total>
					<subtotal>1200</subtotal>
					<descuentos>0</descuentos>
					<impuentos>IVA</impuentos>
					<total-pago>1200</total-pago>
					<moneda>USD</moneda>
				</total>
				<condiciones-pago>transferencia</condiciones-pago>
				<plazo-de-pago-dias>15</plazo-de-pago-dias>
				<notas-pago>ninguno</notas-pago>
			</numero-factura>
			<numero-factura>
				<numero>001</numero>
				<fecha>2025-08-30</fecha>		
				<vendedor>
					<codigo>2025209401</codigo>
					<nombre>Johan Sebastian Martinez</nombre>
					<telefono>3015778544</telefono>
				</vendedor>
				<cliente>
					<nombre>Carlos López</nombre>
					<nit>900124451</nit>
					<cedula>34655721</cedula>
					<ciudad>Bogotá</ciudad>
					<direccion>Calle 34 # 74 13 </direccion>
					<telefono>3418997544</telefono>
				</cliente>
				<servicio>
					<descripcion>
					Conusltoría y Aseoría en el Mercado ambiental
					</descripcion>
					<cantidad>1</cantidad>
					<precio>500</precio>
				</servicio>
				<servicio>
					<descripcion>
					Evaluación de áreas para compensaciones
					</descripcion>
					<cantidad>3</cantidad>
					<precio>200</precio>
				</servicio>
				<servicio>
					<descripcion>
					Levantamiento fotogrametria
					</descripcion>
					<cantidad>1</cantidad>
					<precio>500</precio>
				</servicio>
				<total>
					<subtotal>1200</subtotal>
					<descuentos>0</descuentos>
					<impuentos>IVA</impuentos>
					<total-pago>1200</total-pago>
					<moneda>USD</moneda>
				</total>
				<condiciones-pago>transferencia</condiciones-pago>
				<plazo-de-pago-dias>15</plazo-de-pago-dias>
				<notas-pago>ninguno</notas-pago>
			</numero-factura><numero-factura>
				<numero>001</numero>
				<fecha>2025-08-30</fecha>		
				<vendedor>
					<codigo>2025209401</codigo>
					<nombre>Johan Sebastian Martinez</nombre>
					<telefono>3015778544</telefono>
				</vendedor>
				<cliente>
					<nombre>Cristian Montealegre</nombre>
					<nit>900124734</nit>
					<cedula>34655721</cedula>
					<ciudad>Villavicencio</ciudad>
					<direccion>Calle 34 # 74 13 </direccion>
					<telefono>3418997544</telefono>
				</cliente>
				<servicio>
					<descripcion>
					Conusltoría y Aseoría en el Mercado ambiental
					</descripcion>
					<cantidad>1</cantidad>
					<precio>500</precio>
				</servicio>
				<servicio>
					<descripcion>
					Evaluación de áreas para compensaciones
					</descripcion>
					<cantidad>3</cantidad>
					<precio>200</precio>
				</servicio>
				<servicio>
					<descripcion>
					Levantamiento fotogrametria
					</descripcion>
					<cantidad>1</cantidad>
					<precio>500</precio>
				</servicio>
				<total>
					<subtotal>1200</subtotal>
					<descuentos>0</descuentos>
					<impuentos>IVA</impuentos>
					<total-pago>1200</total-pago>
					<moneda>USD</moneda>
				</total>
				<condiciones-pago>transferencia</condiciones-pago>
				<plazo-de-pago-dias>15</plazo-de-pago-dias>
				<notas-pago>ninguno</notas-pago>
			</numero-factura><numero-factura>
				<numero>001</numero>
				<fecha>2025-08-30</fecha>		
				<vendedor>
					<codigo>2025209401</codigo>
					<nombre>Johan Sebastian Martinez</nombre>
					<telefono>3015778544</telefono>
				</vendedor>
				<cliente>
					<nombre>Alfredo Ruiz</nombre>
					<nit>900143798</nit>
					<cedula>34655721</cedula>
					<ciudad>Ibagué</ciudad>
					<direccion>Calle 34 # 74 13 </direccion>
					<telefono>3418997544</telefono>
				</cliente>
				<servicio>
					<descripcion>
					Conusltoría y Aseoría en el Mercado ambiental
					</descripcion>
					<cantidad>1</cantidad>
					<precio>500</precio>
				</servicio>
				<servicio>
					<descripcion>
					Evaluación de áreas para compensaciones
					</descripcion>
					<cantidad>3</cantidad>
					<precio>200</precio>
				</servicio>
				<servicio>
					<descripcion>
					Levantamiento fotogrametria
					</descripcion>
					<cantidad>1</cantidad>
					<precio>500</precio>
				</servicio>
				<total>
					<subtotal>1200</subtotal>
					<descuentos>0</descuentos>
					<impuentos>IVA</impuentos>
					<total-pago>1200</total-pago>
					<moneda>USD</moneda>
				</total>
				<condiciones-pago>transferencia</condiciones-pago>
				<plazo-de-pago-dias>15</plazo-de-pago-dias>
				<notas-pago>ninguno</notas-pago>
			</numero-factura>	
			<numero-factura>
				<numero>001</numero>
				<fecha>2025-08-30</fecha>		
				<vendedor>
					<codigo>2025209401</codigo>
					<nombre>Johan Sebastian Martinez</nombre>
					<telefono>3015778544</telefono>
				</vendedor>
				<cliente>
					<nombre>Pepito Perez</nombre>
					<nit>900147798</nit>
					<cedula>34655721</cedula>
					<ciudad>Barranquilla</ciudad>
					<direccion>Calle 34 # 74 13 </direccion>
					<telefono>3418997544</telefono>
				</cliente>
				<servicio>
					<descripcion>
					Conusltoría y Aseoría en el Mercado ambiental
					</descripcion>
					<cantidad>1</cantidad>
					<precio>500</precio>
				</servicio>
				<servicio>
					<descripcion>
					Evaluación de áreas para compensaciones
					</descripcion>
					<cantidad>3</cantidad>
					<precio>200</precio>
				</servicio>
				<servicio>
					<descripcion>
					Levantamiento fotogrametria
					</descripcion>
					<cantidad>1</cantidad>
					<precio>500</precio>
				</servicio>
				<total>
					<subtotal>1200</subtotal>
					<descuentos>0</descuentos>
					<impuentos>IVA</impuentos>
					<total-pago>1200</total-pago>
					<moneda>USD</moneda>
				</total>
				<condiciones-pago>transferencia</condiciones-pago>
				<plazo-de-pago-dias>15</plazo-de-pago-dias>
				<notas-pago>ninguno</notas-pago>
			</numero-factura>	
			<numero-factura>
				<numero>001</numero>
				<fecha>2025-08-30</fecha>		
				<vendedor>
					<codigo>2025209401</codigo>
					<nombre>Johan Sebastian Martinez</nombre>
					<telefono>3015778544</telefono>
				</vendedor>
				<cliente>
					<nombre>Juan Rodriguez</nombre>
					<nit>900121498</nit>
					<cedula>34655721</cedula>
					<ciudad>Bucaranamga</ciudad>
					<direccion>Calle 34 # 74 13 </direccion>
					<telefono>3418997544</telefono>
				</cliente>
				<servicio>
					<descripcion>
					Conusltoría y Aseoría en el Mercado ambiental
					</descripcion>
					<cantidad>1</cantidad>
					<precio>500</precio>
				</servicio>
				<servicio>
					<descripcion>
					Evaluación de áreas para compensaciones
					</descripcion>
					<cantidad>3</cantidad>
					<precio>200</precio>
				</servicio>
				<servicio>
					<descripcion>
					Levantamiento fotogrametria
					</descripcion>
					<cantidad>1</cantidad>
					<precio>500</precio>
				</servicio>
				<total>
					<subtotal>1200</subtotal>
					<descuentos>0</descuentos>
					<impuentos>IVA</impuentos>
					<total-pago>1200</total-pago>
					<moneda>USD</moneda>
				</total>
				<condiciones-pago>transferencia</condiciones-pago>
				<plazo-de-pago-dias>15</plazo-de-pago-dias>
				<notas-pago>ninguno</notas-pago>
			</numero-factura>	
			<numero-factura>
				<numero>001</numero>
				<fecha>2025-08-30</fecha>		
				<vendedor>
					<codigo>2025209401</codigo>
					<nombre>Johan Sebastian Martinez</nombre>
					<telefono>3015778544</telefono>
				</vendedor>
				<cliente>
					<nombre>Laura Martinez</nombre>
					<nit>900121638</nit>
					<cedula>34655721</cedula>
					<ciudad>Popayán</ciudad>
					<direccion>Calle 34 # 74 13 </direccion>
					<telefono>3418997544</telefono>
				</cliente>
				<servicio>
					<descripcion>
					Conusltoría y Aseoría en el Mercado ambiental
					</descripcion>
					<cantidad>1</cantidad>
					<precio>500</precio>
				</servicio>
				<servicio>
					<descripcion>
					Evaluación de áreas para compensaciones
					</descripcion>
					<cantidad>3</cantidad>
					<precio>200</precio>
				</servicio>
				<servicio>
					<descripcion>
					Levantamiento fotogrametria
					</descripcion>
					<cantidad>1</cantidad>
					<precio>500</precio>
				</servicio>
				<total>
					<subtotal>1200</subtotal>
					<descuentos>0</descuentos>
					<impuentos>IVA</impuentos>
					<total-pago>1200</total-pago>
					<moneda>USD</moneda>
				</total>
				<condiciones-pago>transferencia</condiciones-pago>
				<plazo-de-pago-dias>15</plazo-de-pago-dias>
				<notas-pago>ninguno</notas-pago>
			</numero-factura>	
			<numero-factura>
				<numero>001</numero>
				<fecha>2025-08-30</fecha>		
				<vendedor>
					<codigo>2025209401</codigo>
					<nombre>Johan Sebastian Martinez</nombre>
					<telefono>3015778544</telefono>
				</vendedor>
				<cliente>
					<nombre>Elena Bejarano</nombre>
					<nit>900147898</nit>
					<cedula>34655721</cedula>
					<ciudad>Valledupar</ciudad>
					<direccion>Calle 34 # 74 13 </direccion>
					<telefono>3418997544</telefono>
				</cliente>
				<servicio>
					<descripcion>
					Conusltoría y Aseoría en el Mercado ambiental
					</descripcion>
					<cantidad>1</cantidad>
					<precio>500</precio>
				</servicio>
				<servicio>
					<descripcion>
